
//Auth Action Types

const CLEAR_AUTH = 'CLEAR_AUTH';
const AUTH_REQUEST = 'AUTH_REQUEST';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_ERROR = 'AUTH_ERROR';

//Story Action Types

const STORY_REQUEST = 'STORY_REQUEST';
const STORIES_SUCCESS = 'STORIES_SUCCESS';
const STORY_SUCCESS = 'STORY_SUCCESS';
const STORY_ERROR = 'STORY_ERROR';
const SET_STORY = 'SET_STORY';
const EDIT_STORY = 'EDIT_STORY';
const ADD_STORY = 'ADD_STORY';

export {
	CLEAR_AUTH,
	AUTH_REQUEST,
	AUTH_SUCCESS,
	AUTH_ERROR,

	STORY_REQUEST,
	STORIES_SUCCESS,
	STORY_SUCCESS,
	STORY_ERROR,
	SET_STORY,
	EDIT_STORY,
	ADD_STORY,
};
